USE [master]
GO

/****** Object:  Database [LearnSQL]    Script Date: 07/22/2022 10:26:46 ******/
DROP DATABASE [LearnSQL]
GO

/****** Object:  Database [LearnSQL]    Script Date: 07/22/2022 10:26:46 ******/
CREATE DATABASE [LearnSQL]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LearnSQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LearnSQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LearnSQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LearnSQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LearnSQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LearnSQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [LearnSQL] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LearnSQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LearnSQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LearnSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LearnSQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LearnSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LearnSQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LearnSQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LearnSQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LearnSQL] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LearnSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LearnSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LearnSQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LearnSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LearnSQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LearnSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LearnSQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LearnSQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LearnSQL] SET  MULTI_USER 
GO

ALTER DATABASE [LearnSQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LearnSQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LearnSQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LearnSQL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LearnSQL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LearnSQL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LearnSQL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LearnSQL] SET  READ_WRITE 
GO

