-- SELECT colums FROM table_name WHERE conditions
-- 1. lấy tất cả các cột dữ liệu trong bảng Student
-- 2. lấy mã sv, tên sv, địa chỉ sv trong bảng Student
-- 3. lấy mã sv, tên sv, địa chỉ sv, chuyên ngành sv trong bảng sv sao sv học ngành CNTT
-- 4. lây mã, tên sv của các sv ở một địa chỉ cho trước